apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-my5grantester-db-filler
  namespace: open5gs
  labels:
    epc-mode: my5grantester-db-filler
  spec:
    replicas: 1
    selector:
      matchLabels:
        epc-mode: my5grantester-db-filler 
    template:
      metadata:
        labels:
          epc-mode: my5grantester-db-filler
      spec:
        nodeSelector:
          kubernetes.io/arch: amd64
          kubernetes.io/hostname: molejo
        containers:
          - name: my5grantester-db-filler
            image: lafschierholt/my5grantester-db-filler
            volumeMounts:
              - name: open5gs-my5grantester-db-filler-database
                mountPath: my5grantester-db-filler/data/database.json
                subPath: "database.json"
              - name: open5gs-my5grantester-db-filler-subscribers
                mountPath: my5grantester-db-filler/data/subscribers.json
                subPath: "subscribers.json"
            environment: 
              - NUM_DEVICES: 10
        volumes:
          - name: open5gs-my5grantester-db-filler-config
            configMap:
              name: open5gs-my5grantester-db-filler-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-my5grantester-db-filler-data
  namespace: open5gs
  labels:
    epc-mode: open5gs-my5grantester-db-filler
data:
  database.json: |
    {
      "host": "172.22.0.2:27017",
      "database": "open5gs",
      "collections": [
        {
          "collection": "subscribers",
          "filename": "subscribers.json"
        }
      ]
    }
  subscribers.json: |
    [{
      "imsi": "$(MCC)$(MNC)$(MSIN)",
      "subscribed_rau_tau_timer": 12,
      "network_access_mode": 2,
      "subscriber_status": 0,
      "access_restriction_data": 32,
      "slice": [
        {
          "sst": $(SST_INT),
          "default_indicator": true,
          "sd": "$(SD)",
          "session": [
            {
              "name": "$(DNN)",
              "type": 3,
              "pcc_rule": [],
              "ambr": {
                "uplink": {
                  "value": 1,
                  "unit": 3
                },
                "downlink": {
                  "value": 1,
                  "unit": 3
                }
              },
              "qos": {
                "index": 9,
                "arp": {
                  "priority_level": 8,
                  "pre_emption_capability": 1,
                  "pre_emption_vulnerability": 1
                }
              }
            }
          ]
        }
      ],
      "ambr": {
        "uplink": {
          "value": 1,
          "unit": 3
        },
        "downlink": {
          "value": 1,
          "unit": 3
        }
      },
      "security": {
        "k": "$(KEY)",
        "amf": "$(AMF)",
        "op": null,
        "opc": "$(OPC)",
        "sqn": 32
      },
      "msisdn": [],
      "schema_version": 1
    }]

    