apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-my5grantester-db-filler
  namespace: open5gs
  labels:
    epc-mode: my5grantester-db-filler
  spec:
    replicas: 1
    selector:
      matchLabels:
        epc-mode: my5grantester-db-filler 
    template:
      metadata:
        labels:
          epc-mode: my5grantester-db-filler
      spec:
        nodeSelector:
          kubernetes.io/arch: amd64
          kubernetes.io/hostname: kiss
        containers:
          - name: my5grantester-db-filler
            image: lafschierholt/my5grantester-db-filler
            env: 
              - name: "NUM_DEVICES"
                value: 10
            command: ["sleep", "1d"]
            # volumeMounts:
            #   - name: open5gs-my5grantester-db-filler-database
            #     mountPath: my5grantester-db-filler/data/database.json
            #     subPath: "database.json"
            
        # volumes:
        #   - name: open5gs-my5grantester-db-filler-config
        #     configMap:
        #       name: open5gs-my5grantester-db-filler-config
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: open5gs-my5grantester-db-filler-data
#   namespace: open5gs
#   labels:
#     epc-mode: open5gs-my5grantester-db-filler
# data: